name: Auto Update VPN

concurrency:
  group: vpn-manager-lock
  cancel-in-progress: false

on:
  schedule:
    - cron: '0 */2 * * *'  # Запуск каждые 2 часа (00:00, 02:00 и т.д.)
  workflow_dispatch:       # Оставляет кнопку для ручного запуска

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write # Важно: разрешаем боту изменять файлы в репо
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # ТЕПЕРЬ СТАВИМ ТУТ (когда Python уже готов)
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests cryptography

      - name: 🌪️ Setup "Censorship" Environment
        run: |
          sudo tc qdisc add dev eth0 root netem delay 150ms 20ms loss 5%
          sudo ifconfig eth0 mtu 1280
      
      - name: Run checker
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: python check.py

      - name: Run checker
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          GH_PROMPT_DISABLED: 1
          GITHUB_REPOSITORY: ${{ github.repository }} # Даем доступ к управлению задачами
        run: python check.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "Checker-Bot"
          git config --global user.email "bot@github.com"
          
          # 1. Добавляем и СРАЗУ коммитим локально (это очистит индекс)
          git add .
          git commit -m "Auto-update: DB and Subscription" || echo "No changes to commit"
          
          # 2. Теперь подтягиваем изменения из репозитория
          # Стратегия -X theirs скажет гиту: "Если есть конфликт в файлах, мои (новые) важнее"
          git pull --rebase -X theirs origin main
          
          # 3. Пушим
          git push origin main

      - name: 🌪️ Setup "Censorship" Environment
        run: |
          # Имитируем типичную мобильную сеть в РФ: 
          # Задержка 150мс, потеря 5% пакетов, ограничение MTU
          sudo tc qdisc add dev eth0 root netem delay 150ms 20ms loss 5%
          # Уменьшаем MTU, чтобы проверить фрагментацию Reality
          sudo ifconfig eth0 mtu 1280
