name: Server Monitor (Executioner)

concurrency:
  group: vpn-manager-lock
  cancel-in-progress: false
  
on:
  schedule:
    - cron: '*/15 * * * *' # Запуск каждые 15 минут
  workflow_run:           # ПО СИГНАЛУ
    workflows: ["Auto Update VPN"] # Название твоего основного воркфлоу
    types:
      - completed
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write # РАЗРЕШАЕМ ПРАВИТЬ ФАЙЛЫ (блокировка/удаление)
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Monitor
        run: python monitor.py

      - name: Save Clean Lists
        run: |
          git config --global user.name "Monitor-Bot"
          git config --global user.email "bot@github.com"
          
          # Добавляем изменения
          git add .
          
          # Коммитим, только если есть что коммитить
          git commit -m "Monitor: Cleaned dead servers and updated Blacklist" || echo "No changes to commit"
          
          # КЛЮЧЕВОЙ МОМЕНТ: Забираем изменения чекера, если они появились за время работы монитора
          # Используем rebase, чтобы наши правки легли поверх правок чекера
          git pull --rebase -X theirs origin main
          
          # Теперь пушим без конфликтов
          git push origin main
