name: 🔄 Update pinned.txt

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 📂 Checkout
        uses: actions/checkout@v4

      - name: ⬇️ Download latest file
        run: |
          mkdir -p test1
          curl -sSL "https://gitverse.ru/api/repos/RoGo/mobile-whitelist/raw/branch/master/mobile-whitelist-1.txt" -o test1/pinned.txt

      - name: 🔍 Check for changes
        id: diff
        run: |
          git add test1/pinned.txt
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: 💾 Commit & push
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update pinned.txt"
          git push
